// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/protoc/serverdata.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Unit  string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	// time since unix epoch in MICROSECONDS
	TimeUs        uint64    `protobuf:"varint,3,opt,name=time_us,json=timeUs,proto3" json:"time_us,omitempty"`
	Values        []float32 `protobuf:"fixed32,4,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerData) Reset() {
	*x = ServerData{}
	mi := &file_pkg_protoc_serverdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerData) ProtoMessage() {}

func (x *ServerData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoc_serverdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerData.ProtoReflect.Descriptor instead.
func (*ServerData) Descriptor() ([]byte, []int) {
	return file_pkg_protoc_serverdata_proto_rawDescGZIP(), []int{0}
}

func (x *ServerData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ServerData) GetTimeUs() uint64 {
	if x != nil {
		return x.TimeUs
	}
	return 0
}

func (x *ServerData) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_pkg_protoc_serverdata_proto protoreflect.FileDescriptor

const file_pkg_protoc_serverdata_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/protoc/serverdata.proto\x12\rserverdata.v2\"^\n" +
	"\n" +
	"ServerData\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x17\n" +
	"\atime_us\x18\x03 \x01(\x04R\x06timeUs\x12\x16\n" +
	"\x06values\x18\x04 \x03(\x02R\x06valuesJ\x04\b\x01\x10\x02R\x05valueB/Z-github.com/grafana/mqtt-datasource/pkg/protocb\x06proto3"

var (
	file_pkg_protoc_serverdata_proto_rawDescOnce sync.Once
	file_pkg_protoc_serverdata_proto_rawDescData []byte
)

func file_pkg_protoc_serverdata_proto_rawDescGZIP() []byte {
	file_pkg_protoc_serverdata_proto_rawDescOnce.Do(func() {
		file_pkg_protoc_serverdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protoc_serverdata_proto_rawDesc), len(file_pkg_protoc_serverdata_proto_rawDesc)))
	})
	return file_pkg_protoc_serverdata_proto_rawDescData
}

var file_pkg_protoc_serverdata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_protoc_serverdata_proto_goTypes = []any{
	(*ServerData)(nil), // 0: serverdata.v2.ServerData
}
var file_pkg_protoc_serverdata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protoc_serverdata_proto_init() }
func file_pkg_protoc_serverdata_proto_init() {
	if File_pkg_protoc_serverdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protoc_serverdata_proto_rawDesc), len(file_pkg_protoc_serverdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protoc_serverdata_proto_goTypes,
		DependencyIndexes: file_pkg_protoc_serverdata_proto_depIdxs,
		MessageInfos:      file_pkg_protoc_serverdata_proto_msgTypes,
	}.Build()
	File_pkg_protoc_serverdata_proto = out.File
	file_pkg_protoc_serverdata_proto_goTypes = nil
	file_pkg_protoc_serverdata_proto_depIdxs = nil
}
